/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "demux_dest.v:1" *)
module demux_dest_estr(clk, reset_L, data_in_d0, valid_in_d0, data_in_d1, valid_in_d1, valid_in, data_in);
  (* src = "demux_dest.v:46" *)
  wire [5:0] _00_;
  (* src = "demux_dest.v:46" *)
  wire [5:0] _01_;
  (* src = "demux_dest.v:46" *)
  wire _02_;
  (* src = "demux_dest.v:46" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  (* src = "demux_dest.v:5" *)
  input clk;
  (* src = "demux_dest.v:12" *)
  input [5:0] data_in;
  (* src = "demux_dest.v:7" *)
  output [5:0] data_in_d0;
  (* src = "demux_dest.v:9" *)
  output [5:0] data_in_d1;
  (* src = "demux_dest.v:6" *)
  input reset_L;
  (* src = "demux_dest.v:21" *)
  wire selector;
  (* src = "demux_dest.v:11" *)
  input valid_in;
  (* src = "demux_dest.v:8" *)
  output valid_in_d0;
  (* src = "demux_dest.v:10" *)
  output valid_in_d1;
  NOT _34_ (
    .A(valid_in),
    .Y(_04_)
  );
  NAND _35_ (
    .A(reset_L),
    .B(data_in[4]),
    .Y(_05_)
  );
  NOR _36_ (
    .A(_05_),
    .B(_04_),
    .Y(_03_)
  );
  NOT _37_ (
    .A(reset_L),
    .Y(_06_)
  );
  NOR _38_ (
    .A(_06_),
    .B(data_in[4]),
    .Y(_07_)
  );
  NAND _39_ (
    .A(_07_),
    .B(data_in_d1[0]),
    .Y(_08_)
  );
  NAND _40_ (
    .A(_03_),
    .B(data_in[0]),
    .Y(_09_)
  );
  NAND _41_ (
    .A(_09_),
    .B(_08_),
    .Y(_01_[0])
  );
  NAND _42_ (
    .A(_07_),
    .B(data_in_d1[1]),
    .Y(_10_)
  );
  NAND _43_ (
    .A(_03_),
    .B(data_in[1]),
    .Y(_11_)
  );
  NAND _44_ (
    .A(_11_),
    .B(_10_),
    .Y(_01_[1])
  );
  NAND _45_ (
    .A(_07_),
    .B(data_in_d1[2]),
    .Y(_12_)
  );
  NAND _46_ (
    .A(_03_),
    .B(data_in[2]),
    .Y(_13_)
  );
  NAND _47_ (
    .A(_13_),
    .B(_12_),
    .Y(_01_[2])
  );
  NAND _48_ (
    .A(_07_),
    .B(data_in_d1[3]),
    .Y(_14_)
  );
  NAND _49_ (
    .A(_03_),
    .B(data_in[3]),
    .Y(_15_)
  );
  NAND _50_ (
    .A(_15_),
    .B(_14_),
    .Y(_01_[3])
  );
  NOT _51_ (
    .A(data_in[4]),
    .Y(_16_)
  );
  NOR _52_ (
    .A(_06_),
    .B(_16_),
    .Y(_17_)
  );
  NAND _53_ (
    .A(_17_),
    .B(valid_in),
    .Y(_18_)
  );
  NAND _54_ (
    .A(_07_),
    .B(data_in_d1[4]),
    .Y(_19_)
  );
  NAND _55_ (
    .A(_19_),
    .B(_18_),
    .Y(_01_[4])
  );
  NAND _56_ (
    .A(_07_),
    .B(data_in_d1[5]),
    .Y(_20_)
  );
  NAND _57_ (
    .A(_03_),
    .B(data_in[5]),
    .Y(_21_)
  );
  NAND _58_ (
    .A(_21_),
    .B(_20_),
    .Y(_01_[5])
  );
  NAND _59_ (
    .A(reset_L),
    .B(valid_in),
    .Y(_22_)
  );
  NOR _60_ (
    .A(_22_),
    .B(data_in[4]),
    .Y(_02_)
  );
  NAND _61_ (
    .A(_17_),
    .B(data_in_d0[0]),
    .Y(_23_)
  );
  NAND _62_ (
    .A(_02_),
    .B(data_in[0]),
    .Y(_24_)
  );
  NAND _63_ (
    .A(_24_),
    .B(_23_),
    .Y(_00_[0])
  );
  NAND _64_ (
    .A(_17_),
    .B(data_in_d0[1]),
    .Y(_25_)
  );
  NAND _65_ (
    .A(_02_),
    .B(data_in[1]),
    .Y(_26_)
  );
  NAND _66_ (
    .A(_26_),
    .B(_25_),
    .Y(_00_[1])
  );
  NAND _67_ (
    .A(_17_),
    .B(data_in_d0[2]),
    .Y(_27_)
  );
  NAND _68_ (
    .A(_02_),
    .B(data_in[2]),
    .Y(_28_)
  );
  NAND _69_ (
    .A(_28_),
    .B(_27_),
    .Y(_00_[2])
  );
  NAND _70_ (
    .A(_17_),
    .B(data_in_d0[3]),
    .Y(_29_)
  );
  NAND _71_ (
    .A(_02_),
    .B(data_in[3]),
    .Y(_30_)
  );
  NAND _72_ (
    .A(_30_),
    .B(_29_),
    .Y(_00_[3])
  );
  NOT _73_ (
    .A(data_in_d0[4]),
    .Y(_31_)
  );
  NOR _74_ (
    .A(_05_),
    .B(_31_),
    .Y(_00_[4])
  );
  NAND _75_ (
    .A(_17_),
    .B(data_in_d0[5]),
    .Y(_32_)
  );
  NAND _76_ (
    .A(_02_),
    .B(data_in[5]),
    .Y(_33_)
  );
  NAND _77_ (
    .A(_33_),
    .B(_32_),
    .Y(_00_[5])
  );
  DFF _78_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_in_d0[0])
  );
  DFF _79_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_in_d0[1])
  );
  DFF _80_ (
    .C(clk),
    .D(_00_[2]),
    .Q(data_in_d0[2])
  );
  DFF _81_ (
    .C(clk),
    .D(_00_[3]),
    .Q(data_in_d0[3])
  );
  DFF _82_ (
    .C(clk),
    .D(_00_[4]),
    .Q(data_in_d0[4])
  );
  DFF _83_ (
    .C(clk),
    .D(_00_[5]),
    .Q(data_in_d0[5])
  );
  DFF _84_ (
    .C(clk),
    .D(_02_),
    .Q(valid_in_d0)
  );
  DFF _85_ (
    .C(clk),
    .D(_01_[0]),
    .Q(data_in_d1[0])
  );
  DFF _86_ (
    .C(clk),
    .D(_01_[1]),
    .Q(data_in_d1[1])
  );
  DFF _87_ (
    .C(clk),
    .D(_01_[2]),
    .Q(data_in_d1[2])
  );
  DFF _88_ (
    .C(clk),
    .D(_01_[3]),
    .Q(data_in_d1[3])
  );
  DFF _89_ (
    .C(clk),
    .D(_01_[4]),
    .Q(data_in_d1[4])
  );
  DFF _90_ (
    .C(clk),
    .D(_01_[5]),
    .Q(data_in_d1[5])
  );
  DFF _91_ (
    .C(clk),
    .D(_03_),
    .Q(valid_in_d1)
  );
  assign selector = data_in[4];
endmodule
