/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "fifo_main_pop.v:1" *)
module fifo_main_pop_estr(clk, vc0_full, reset_L, vc1_full, fifo_main_empty, data_in, data_out, valid_in, fifo_rd);
  (* src = "fifo_main_pop.v:29" *)
  wire [5:0] _00_;
  (* src = "fifo_main_pop.v:29" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "fifo_main_pop.v:2" *)
  input clk;
  (* src = "fifo_main_pop.v:7" *)
  input [5:0] data_in;
  (* src = "fifo_main_pop.v:8" *)
  output [5:0] data_out;
  (* src = "fifo_main_pop.v:13" *)
  wire [5:0] data_out_recordar;
  (* src = "fifo_main_pop.v:6" *)
  input fifo_main_empty;
  (* src = "fifo_main_pop.v:10" *)
  output fifo_rd;
  (* src = "fifo_main_pop.v:4" *)
  input reset_L;
  (* src = "fifo_main_pop.v:9" *)
  output valid_in;
  (* src = "fifo_main_pop.v:3" *)
  input vc0_full;
  (* src = "fifo_main_pop.v:5" *)
  input vc1_full;
  NOT _15_ (
    .A(data_in[2]),
    .Y(_02_)
  );
  NOR _16_ (
    .A(vc0_full),
    .B(fifo_main_empty),
    .Y(_03_)
  );
  NOT _17_ (
    .A(reset_L),
    .Y(_04_)
  );
  NOR _18_ (
    .A(_04_),
    .B(vc1_full),
    .Y(_05_)
  );
  NAND _19_ (
    .A(_05_),
    .B(_03_),
    .Y(_06_)
  );
  NOR _20_ (
    .A(_06_),
    .B(_02_),
    .Y(_00_[2])
  );
  NOT _21_ (
    .A(data_in[3]),
    .Y(_07_)
  );
  NOR _22_ (
    .A(_06_),
    .B(_07_),
    .Y(_00_[3])
  );
  NOT _23_ (
    .A(data_in[4]),
    .Y(_08_)
  );
  NOR _24_ (
    .A(_06_),
    .B(_08_),
    .Y(_00_[4])
  );
  NOT _25_ (
    .A(data_in[5]),
    .Y(_09_)
  );
  NOR _26_ (
    .A(_06_),
    .B(_09_),
    .Y(_00_[5])
  );
  NOT _27_ (
    .A(_03_),
    .Y(_10_)
  );
  NOT _28_ (
    .A(vc1_full),
    .Y(_11_)
  );
  NAND _29_ (
    .A(reset_L),
    .B(_11_),
    .Y(_12_)
  );
  NOR _30_ (
    .A(_12_),
    .B(_10_),
    .Y(_01_)
  );
  NOT _31_ (
    .A(data_in[0]),
    .Y(_13_)
  );
  NOR _32_ (
    .A(_06_),
    .B(_13_),
    .Y(_00_[0])
  );
  NOT _33_ (
    .A(data_in[1]),
    .Y(_14_)
  );
  NOR _34_ (
    .A(_06_),
    .B(_14_),
    .Y(_00_[1])
  );
  DFF _35_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out[0])
  );
  DFF _36_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_out[1])
  );
  DFF _37_ (
    .C(clk),
    .D(_00_[2]),
    .Q(data_out[2])
  );
  DFF _38_ (
    .C(clk),
    .D(_00_[3]),
    .Q(data_out[3])
  );
  DFF _39_ (
    .C(clk),
    .D(_00_[4]),
    .Q(data_out[4])
  );
  DFF _40_ (
    .C(clk),
    .D(_00_[5]),
    .Q(data_out[5])
  );
  DFF _41_ (
    .C(clk),
    .D(_01_),
    .Q(fifo_rd)
  );
  assign data_out_recordar = data_in;
  assign valid_in = fifo_rd;
endmodule
