/* Generated by Yosys 0.5+ (git sha1 f13e387, gcc 5.3.1-8ubuntu2 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "maquina_estados_estr.v:1" *)
module maquina_estados_estr(clk, init, UmbralesMFs, UmbralesVCs, UmbralesDs, reset, FIFO_EMPTIES, FIFO_ERRORS, error_out_estr, active_out_estr, idle_out_estr, UmbralMF_estr, UmbralV0_estr, UmbralV1_estr, UmbralD0_estr, UmbralD1_estr);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  (* src = "maquina_estados_estr.v:9" *)
  input [4:0] FIFO_EMPTIES;
  (* src = "maquina_estados_estr.v:10" *)
  input [4:0] FIFO_ERRORS;
  (* src = "maquina_estados_estr.v:18" *)
  output UmbralD0_estr;
  (* src = "maquina_estados_estr.v:19" *)
  output UmbralD1_estr;
  (* src = "maquina_estados_estr.v:15" *)
  output UmbralMF_estr;
  (* src = "maquina_estados_estr.v:16" *)
  output UmbralV0_estr;
  (* src = "maquina_estados_estr.v:17" *)
  output UmbralV1_estr;
  (* src = "maquina_estados_estr.v:7" *)
  input [1:0] UmbralesDs;
  (* src = "maquina_estados_estr.v:5" *)
  input UmbralesMFs;
  (* src = "maquina_estados_estr.v:6" *)
  input [1:0] UmbralesVCs;
  (* src = "maquina_estados_estr.v:13" *)
  output active_out_estr;
  (* src = "maquina_estados_estr.v:3" *)
  input clk;
  (* src = "maquina_estados_estr.v:12" *)
  output error_out_estr;
  (* onehot = 32'd 1 *)
  wire [4:0] estado;
  (* src = "maquina_estados_estr.v:14" *)
  output idle_out_estr;
  (* src = "maquina_estados_estr.v:4" *)
  input init;
  (* src = "maquina_estados_estr.v:8" *)
  input reset;
  NAND _049_ (
    .A(estado[1]),
    .B(reset),
    .Y(_001_)
  );
  NOR _050_ (
    .A(FIFO_ERRORS[1]),
    .B(FIFO_ERRORS[4]),
    .Y(_002_)
  );
  NOT _051_ (
    .A(FIFO_ERRORS[2]),
    .Y(_003_)
  );
  NOT _052_ (
    .A(FIFO_ERRORS[3]),
    .Y(_005_)
  );
  NAND _053_ (
    .A(_005_),
    .B(_003_),
    .Y(_006_)
  );
  NOR _054_ (
    .A(_006_),
    .B(FIFO_ERRORS[0]),
    .Y(_007_)
  );
  NAND _055_ (
    .A(_007_),
    .B(_002_),
    .Y(_008_)
  );
  NOT _056_ (
    .A(reset),
    .Y(_048_)
  );
  NOR _057_ (
    .A(estado[3]),
    .B(estado[4]),
    .Y(_009_)
  );
  NOR _058_ (
    .A(_009_),
    .B(init),
    .Y(_010_)
  );
  NOR _059_ (
    .A(_010_),
    .B(estado[2]),
    .Y(_011_)
  );
  NOR _060_ (
    .A(_011_),
    .B(_048_),
    .Y(_012_)
  );
  NAND _061_ (
    .A(_012_),
    .B(_008_),
    .Y(_013_)
  );
  NAND _062_ (
    .A(_013_),
    .B(_001_),
    .Y(_000_)
  );
  NOT _063_ (
    .A(FIFO_ERRORS[1]),
    .Y(_015_)
  );
  NOR _064_ (
    .A(FIFO_ERRORS[0]),
    .B(FIFO_ERRORS[4]),
    .Y(_016_)
  );
  NAND _065_ (
    .A(_016_),
    .B(_015_),
    .Y(_017_)
  );
  NOR _066_ (
    .A(_017_),
    .B(_006_),
    .Y(_018_)
  );
  NOT _067_ (
    .A(FIFO_EMPTIES[0]),
    .Y(_019_)
  );
  NOT _068_ (
    .A(FIFO_EMPTIES[1]),
    .Y(_020_)
  );
  NAND _069_ (
    .A(_020_),
    .B(_019_),
    .Y(_021_)
  );
  NOT _070_ (
    .A(FIFO_EMPTIES[4]),
    .Y(_023_)
  );
  NOR _071_ (
    .A(FIFO_EMPTIES[3]),
    .B(FIFO_EMPTIES[2]),
    .Y(_024_)
  );
  NAND _072_ (
    .A(_024_),
    .B(_023_),
    .Y(_025_)
  );
  NOR _073_ (
    .A(_025_),
    .B(_021_),
    .Y(_026_)
  );
  NOT _074_ (
    .A(_026_),
    .Y(_027_)
  );
  NAND _075_ (
    .A(_027_),
    .B(_018_),
    .Y(_028_)
  );
  NOT _076_ (
    .A(estado[2]),
    .Y(_029_)
  );
  NOR _077_ (
    .A(_029_),
    .B(_048_),
    .Y(_030_)
  );
  NOT _078_ (
    .A(estado[4]),
    .Y(_031_)
  );
  NOT _079_ (
    .A(init),
    .Y(_032_)
  );
  NAND _080_ (
    .A(reset),
    .B(_032_),
    .Y(_033_)
  );
  NOR _081_ (
    .A(_033_),
    .B(_031_),
    .Y(_034_)
  );
  NOR _082_ (
    .A(_034_),
    .B(_030_),
    .Y(_035_)
  );
  NOR _083_ (
    .A(_035_),
    .B(_028_),
    .Y(_004_)
  );
  NOR _084_ (
    .A(_026_),
    .B(_008_),
    .Y(_036_)
  );
  NOT _085_ (
    .A(estado[3]),
    .Y(_037_)
  );
  NOR _086_ (
    .A(_033_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _087_ (
    .A(_038_),
    .B(_036_),
    .Y(_039_)
  );
  NOT _088_ (
    .A(estado[0]),
    .Y(_040_)
  );
  NOT _089_ (
    .A(_009_),
    .Y(_041_)
  );
  NAND _090_ (
    .A(_041_),
    .B(init),
    .Y(_042_)
  );
  NAND _091_ (
    .A(_042_),
    .B(_040_),
    .Y(_043_)
  );
  NAND _092_ (
    .A(_043_),
    .B(reset),
    .Y(_044_)
  );
  NAND _093_ (
    .A(_044_),
    .B(_039_),
    .Y(_014_)
  );
  NAND _094_ (
    .A(_018_),
    .B(reset),
    .Y(_045_)
  );
  NOT _095_ (
    .A(_011_),
    .Y(_046_)
  );
  NAND _096_ (
    .A(_026_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _097_ (
    .A(_047_),
    .B(_045_),
    .Y(_022_)
  );
  DFF _098_ (
    .C(clk),
    .D(_048_),
    .Q(estado[0])
  );
  DFF _099_ (
    .C(clk),
    .D(_000_),
    .Q(estado[1])
  );
  DFF _100_ (
    .C(clk),
    .D(_022_),
    .Q(estado[2])
  );
  DFF _101_ (
    .C(clk),
    .D(_014_),
    .Q(estado[3])
  );
  DFF _102_ (
    .C(clk),
    .D(_004_),
    .Q(estado[4])
  );
  assign UmbralD0_estr = 1'b0;
  assign UmbralD1_estr = 1'b0;
  assign UmbralMF_estr = 1'b0;
  assign UmbralV0_estr = 1'b0;
  assign UmbralV1_estr = 1'b0;
  assign active_out_estr = estado[4];
  assign error_out_estr = estado[1];
  assign idle_out_estr = estado[2];
endmodule
