/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "pop_delay_vc0.v:1" *)
module pop_delay_vc0_estr(clk, reset_L, d0_full, d1_full, vc0_empty, vc1_empty, vc0_delay, vc0_read, vc1_read);
  (* src = "pop_delay_vc0.v:66" *)
  wire _00_;
  (* src = "pop_delay_vc0.v:66" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "pop_delay_vc0.v:2" *)
  input clk;
  (* src = "pop_delay_vc0.v:4" *)
  input d0_full;
  (* src = "pop_delay_vc0.v:5" *)
  input d1_full;
  (* src = "pop_delay_vc0.v:3" *)
  input reset_L;
  (* src = "pop_delay_vc0.v:8" *)
  output vc0_delay;
  (* src = "pop_delay_vc0.v:6" *)
  input vc0_empty;
  (* src = "pop_delay_vc0.v:9" *)
  output vc0_read;
  (* src = "pop_delay_vc0.v:7" *)
  input vc1_empty;
  (* src = "pop_delay_vc0.v:10" *)
  output vc1_read;
  NAND _06_ (
    .A(d1_full),
    .B(d0_full),
    .Y(_04_)
  );
  NAND _07_ (
    .A(_04_),
    .B(reset_L),
    .Y(_05_)
  );
  NOR _08_ (
    .A(_05_),
    .B(vc0_empty),
    .Y(_01_)
  );
  NOT _09_ (
    .A(vc1_empty),
    .Y(_02_)
  );
  NAND _10_ (
    .A(vc0_empty),
    .B(_02_),
    .Y(_03_)
  );
  NOR _11_ (
    .A(_03_),
    .B(_05_),
    .Y(_00_)
  );
  DFF _12_ (
    .C(clk),
    .D(_00_),
    .Q(vc0_delay)
  );
  DFF _13_ (
    .C(clk),
    .D(_01_),
    .Q(vc0_read)
  );
  assign vc1_read = vc0_delay;
endmodule
